### ISSUE TITLE
 Exception while invoking method 'comments/count' Error: Match error: Expected string, got null

### ISSUE THREAD

**Issue by webmagnets** [komentify/integration-libs#3]
Can you give me an idea of what I need to be looking for to fix this?

Server logs:
```
I20170112-09:40:21.480(-6)? Exception while invoking method 'comments/count' Error: Match error: Expected string, got null
I20170112-09:40:21.480(-6)?     at meteorInstall.node_modules.meteor.check.match.js.exports.check (packages/check.js:57:15)
I20170112-09:40:21.480(-6)?     at [object Object].commentsCount (packages/arkham:comments-ui/lib/collections/methods/comments.js:509:5)
I20170112-09:40:21.481(-6)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1712:12)
I20170112-09:40:21.481(-6)?     at packages/ddp-server/livedata_server.js:711:19
I20170112-09:40:21.481(-6)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170112-09:40:21.481(-6)?     at packages/ddp-server/livedata_server.js:709:40
I20170112-09:40:21.484(-6)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170112-09:40:21.485(-6)?     at packages/ddp-server/livedata_server.js:707:46
I20170112-09:40:21.490(-6)?     at Session.method (packages/ddp-server/livedata_server.js:681:23)
I20170112-09:40:21.490(-6)?     at packages/ddp-server/livedata_server.js:551:43
I20170112-09:40:21.491(-6)? Sanitized and reported to the client as: Match failed [400]
I20170112-09:40:21.492(-6)? 
I20170112-09:40:21.493(-6)? Exception from sub comments/reference id PrxAk69EhGnxHFFag Error: Match error: Expected string, got null
I20170112-09:40:21.493(-6)?     at meteorInstall.node_modules.meteor.check.match.js.exports.check (packages/check.js:57:15)
I20170112-09:40:21.493(-6)?     at Subscription.<anonymous> (packages/arkham:comments-ui/lib/server/publish.js:62:3)
I20170112-09:40:21.493(-6)?     at Subscription.prepareOptions (packages/reywood_publish-composite.js:459:43)
I20170112-09:40:21.493(-6)?     at Subscription._handler (packages/reywood_publish-composite.js:427:46)
I20170112-09:40:21.493(-6)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1712:12)
I20170112-09:40:21.494(-6)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1027:17)
I20170112-09:40:21.494(-6)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:845:9)
I20170112-09:40:21.494(-6)?     at Session.sub (packages/ddp-server/livedata_server.js:617:12)
I20170112-09:40:21.494(-6)?     at packages/ddp-server/livedata_server.js:551:43
I20170112-09:40:21.494(-6)? Sanitized and reported to the client as: Match failed [400]
```

Client logs:
```
Exception while simulating the effect of invoking 'comments/count' errorClass {message: "Match error: Expected string, got undefined", path: "", sanitizedError: errorClass, errorType: "Match.Error", stack: "Error↵    at exports.check (http://localhost:4000/…813922cefaf3c9d7388442268c14f87d2dde795f:3743:12)"} Error
    at exports.check (http://localhost:4000/packages/check.js?hash=63d7478b74cadc04d378bc2266ea8bd1bf6849d8:67:15)
    at DDPCommon.MethodInvocation.commentsCount (http://localhost:4000/packages/arkham_comments-ui.js?hash=f1e768589c684930412b47fecf32e4ef2b1e187e:1066:7)
    at http://localhost:4000/packages/ddp-client.js?hash=bc32a166cd269e06a394f9418e0024d805bab379:3973:25
    at Meteor.EnvironmentVariable.withValue (http://localhost:4000/packages/meteor.js?hash=e3f53db3be730057fed1a5f709ecd5fc7cae1229:1077:17)
    at Connection.apply (http://localhost:4000/packages/ddp-client.js?hash=bc32a166cd269e06a394f9418e0024d805bab379:3964:54)
    at Connection.call (http://localhost:4000/packages/ddp-client.js?hash=bc32a166cd269e06a394f9418e0024d805bab379:3840:17)
    at Object.getCount (http://localhost:4000/packages/arkham_comments-ui.js?hash=f1e768589c684930412b47fecf32e4ef2b1e187e:3832:21)
    at Blaze.View.<anonymous> (http://localhost:4000/packages/arkham_comments-ui.js?hash=f1e768589c684930412b47fecf32e4ef2b1e187e:1967:14)
    at http://localhost:4000/packages/blaze.js?hash=813922cefaf3c9d7388442268c14f87d2dde795f:1933:20
    at Function.Template._withTemplateInstanceFunc (http://localhost:4000/packages/blaze.js?hash=813922cefaf3c9d7388442268c14f87d2dde795f:3743:12)
meteor.js?hash=e3f53db…:930 Exception from Tracker afterFlush function:
meteor.js?hash=e3f53db…:930 TypeError: Cannot read property 'referenceId' of undefined
    at Blaze.View.<anonymous> (commentsTextarea.js:35)
    at blaze.js?hash=813922c…:1933
    at Function.Template._withTemplateInstanceFunc (blaze.js?hash=813922c…:3743)
    at blaze.js?hash=813922c…:1931
    at Object.Blaze._withCurrentView (blaze.js?hash=813922c…:2270)
    at viewAutorun (blaze.js?hash=813922c…:1930)
    at Tracker.Computation._compute (tracker.js?hash=9f8a0ce…:339)
    at new Tracker.Computation (tracker.js?hash=9f8a0ce…:229)
    at Object.Tracker.autorun (tracker.js?hash=9f8a0ce…:604)
    at Blaze.View.autorun (blaze.js?hash=813922c…:1943)
c74853c….js?meteor_js_resource=true:3 Exception in delivering result of invoking 'apps.embed-data': Error
    at https://www.komentify.io/c74853c2ee337bb6cf66176d03134599a7ea639e.js?meteor_js_resource=true:315:24293
    at c._callback (https://www.komentify.io/c74853c2ee337bb6cf66176d03134599a7ea639e.js?meteor_js_resource=true:3:7449)
    at c._maybeInvokeCallback (https://www.komentify.io/c74853c2ee337bb6cf66176d03134599a7ea639e.js?meteor_js_resource=true:84:9141)
    at c.receiveResult (https://www.komentify.io/c74853c2ee337bb6cf66176d03134599a7ea639e.js?meteor_js_resource=true:84:9449)
    at o._livedata_result (https://www.komentify.io/c74853c2ee337bb6cf66176d03134599a7ea639e.js?meteor_js_resource=true:84:21612)
    at o (https://www.komentify.io/c74853c2ee337bb6cf66176d03134599a7ea639e.js?meteor_js_resource=true:84:6987)
    at https://www.komentify.io/c74853c2ee337bb6cf66176d03134599a7ea639e.js?meteor_js_resource=true:84:608
    at Array.forEach (native)
    at Function.A.each.A.forEach (https://www.komentify.io/c74853c2ee337bb6cf66176d03134599a7ea639e.js?meteor_js_resource=true:1:865)
    at C.t.socket.onmessage (https://www.komentify.io/c74853c2ee337bb6cf66176d03134599a7ea639e.js?meteor_js_resource=true:84:566)
```

**Comment by matteodem** [comment]
How did you use the integration library? Can you show me some code snippets?

**Comment by webmagnets** [comment]
I was using this: https://atmospherejs.com/arkham/comments-ui

I switched to this: https://atmospherejs.com/arkham/komentify

Now everything seems to be working.
